# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DistanceCalculator' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DistanceCalculator

  pod 'DistanceGetter' , '~> 0.1'
  target 'DistanceCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DistanceCalculatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
