# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyConversion' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CurrencyConversion

  target 'CurrencyConversionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyConversionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'CurrencyRequest', '~> 0.1'


end
